function [xfs,Xnn] = ctfs(t,Xn,no,fo,N)

    %  ctfs.m
    %  [xfs] = ctfs(t,Xn,no,fo,N)
    %  
    % Computes the Fourier series approximation xfs(t) of
    %    the signal x(t) over the the time interval t from
    %    2N+1 of the Fourier series coefficients Xn.
    %    (centered on X(no)=Xo).
    %
    %  Gordon E. Carlson  University of Missouri-Rolla
    %
    %    t : time array
    %    x : signal
    %    Xn: Fourier series coefficients generated by ctfsc
    %    no: center value generated by ctfsc
    %    fo: frequency center value generated by ctfsc
    %    N : (desired number of terms -1)/2
    %
    %    The plotting segment of this function has been changed.
    %
    %  modified May 2002 by Laura Tomaja University of Misouri-Rolla

        ns=size(t,2);  j=sqrt(-1);
        for k=1:2*N+1;  
            Xnn(k)=Xn(k+no-N-1);  
        end;
        n=(meshgrid(-N:N,1:ns))';
        tm=meshgrid(t,1:2*N+1);
        Xm=(meshgrid(Xnn,1:ns)).';
        xfs=real(sum(Xm.*exp(j*2*pi*n*fo.*tm)));