t = -15:0.001:15;
x = sign(sin(t));

figure();
plot(t,x);

dfm = 0.001;
[f,X,N,no] = ctft(t,x,dfm);

figure();
plot(f,abs(real(X)));

    %    t : time array
    %    x : signal
    %    Xn: Fourier series coefficients generated by ctfsc
    %    no: center value generated by ctfsc
    %    fo: frequency center value generated by ctfsc
    %    N : (desired number of terms -1)/2
    
[xfs,Xnn] = ctfs(t,Xn,no,fo,N)